### ISSUE TITLE
Remove Theme Template Files from Repo

### ISSUE THREAD

**Issue by arisac** [newtonproject/newbridge.network#34]
Theme Template should be used as a dependency not included in this repo.

**Comment by arisac** [comment]
Theme is not ready for a fully independent release. Still some features for `testing` in this repo.

Considering moving Theme to a new repo and use as a git submodule in here.

**Comment by arisac** [comment]
Theme file will be moved to https://github.com/newtonproject/newdocs-hugo once #32 #33 and clean up complete

**Comment by VieYang** [comment]
cool

**Comment by arisac** [comment]
Please check https://github.com/newtonproject/newbridge.network/tree/pr-theme-submodule

@weixuefeng @VieYang
